#!/usr/bin/env python3
"""Generate the static, filesystem-free MoonBit conformance input."""
import argparse
import json
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def cases():
    result = []
    official = json.loads((ROOT / 'third_party/json-logic-js/tests.json').read_text())
    for i, row in enumerate(x for x in official if isinstance(x, list)):
        result.append((f'official/{i:03d}', row[0], row[1]))
    for row in json.loads((ROOT / 'tests/edge_cases.json').read_text()):
        result.append((row['id'], row['rule'], row['data']))
    return result

def generated():
    lines = ['// Generated by tools/generate_cases.py; edit JSON fixtures instead.', '///|', 'fn cases() -> Array[(String, String, String)] {', '  [']
    for id_, rule, data in cases():
        encoded = [id_, json.dumps(rule, ensure_ascii=False, separators=(',', ':')), json.dumps(data, ensure_ascii=False, separators=(',', ':'))]
        lines.append('    (' + ', '.join(json.dumps(x, ensure_ascii=False) for x in encoded) + '),')
    return '\n'.join(lines + ['  ]', '}', ''])

if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    path = ROOT / 'compat/src/cases.mbt'
    if args.check:
        if re.findall(r'"(?:\\.|[^"\\])*"', path.read_text()) != re.findall(r'"(?:\\.|[^"\\])*"', generated()):
            raise SystemExit('Generated fixtures are stale; run python3 tools/generate_cases.py')
    else:
        path.write_text(generated())
